---
- hosts: all
  become: yes

  vars_files:
    - ../sites.yml
    - vars/firewall.yml
    - vars/nginx.params.yml
    - vars/php.yml

  roles:
    - AerisCloud.repos
    - init
    - geerlingguy.firewall
    - geerlingguy.nginx
    - geerlingguy.php
